name: Generate Snake

on:
  schedule: # Run at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: ana-dev # substitua pelo seu username do GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "Ana"
          git config --global user.email "anaoliveira4267@gmail.com"
          git add -A
          git commit -m "Updated snake animation"
          git push
